# Docker Compose configuration for frontend, backend, PostgreSQL

version: "3.9"

services:
  db:
    image: postgres:16
    container_name: newsite_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-newsite}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-newsite}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: newsite_backend
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: newsite_frontend
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  db_data:
